CREATE TABLE "GCG_4016_MAIN"(
 "BIRUNID" BIGINT,
 "TRMNL" CHAR(3),
 "QUOTE_NO" CHAR(7),
 "QUOTE_LINE" CHAR(4),
 "CUSTOMER" CHAR(6),
 "NAME_CUSTOMER" CHAR(40),
 "SALESPERSON" CHAR(3),
 "EXTENSION" NUMERIC(16,6),
 "FLAG_STATUS" CHAR(1),
 "COMMENTS" CHAR(30));
